// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/greet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	mi := &file_proto_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_proto_greet_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_greet_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_greet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_greet_proto_rawDescGZIP(), []int{2}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NameList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameList) Reset() {
	*x = NameList{}
	mi := &file_proto_greet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameList) ProtoMessage() {}

func (x *NameList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameList.ProtoReflect.Descriptor instead.
func (*NameList) Descriptor() ([]byte, []int) {
	return file_proto_greet_proto_rawDescGZIP(), []int{3}
}

func (x *NameList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type MessagesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesList) Reset() {
	*x = MessagesList{}
	mi := &file_proto_greet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesList) ProtoMessage() {}

func (x *MessagesList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesList.ProtoReflect.Descriptor instead.
func (*MessagesList) Descriptor() ([]byte, []int) {
	return file_proto_greet_proto_rawDescGZIP(), []int{4}
}

func (x *MessagesList) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_greet_proto protoreflect.FileDescriptor

const file_proto_greet_proto_rawDesc = "" +
	"\n" +
	"\x11proto/greet.proto\"\t\n" +
	"\aNoParam\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\bNameList\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"*\n" +
	"\fMessagesList\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages2\xed\x01\n" +
	"\rGreetServices\x12$\n" +
	"\bSayHello\x12\b.NoParam\x1a\x0e.HelloResponse\x126\n" +
	"\x17SayHelloServerStreaming\x12\t.NameList\x1a\x0e.HelloResponse0\x01\x129\n" +
	"\x17SayHelloClientStreaming\x12\r.HelloRequest\x1a\r.MessagesList(\x01\x12C\n" +
	"\x1eSayHelloBidirectionalStreaming\x12\r.HelloRequest\x1a\x0e.HelloResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_greet_proto_rawDescOnce sync.Once
	file_proto_greet_proto_rawDescData []byte
)

func file_proto_greet_proto_rawDescGZIP() []byte {
	file_proto_greet_proto_rawDescOnce.Do(func() {
		file_proto_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greet_proto_rawDesc), len(file_proto_greet_proto_rawDesc)))
	})
	return file_proto_greet_proto_rawDescData
}

var file_proto_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_greet_proto_goTypes = []any{
	(*NoParam)(nil),       // 0: NoParam
	(*HelloResponse)(nil), // 1: HelloResponse
	(*HelloRequest)(nil),  // 2: HelloRequest
	(*NameList)(nil),      // 3: NameList
	(*MessagesList)(nil),  // 4: MessagesList
}
var file_proto_greet_proto_depIdxs = []int32{
	0, // 0: GreetServices.SayHello:input_type -> NoParam
	3, // 1: GreetServices.SayHelloServerStreaming:input_type -> NameList
	2, // 2: GreetServices.SayHelloClientStreaming:input_type -> HelloRequest
	2, // 3: GreetServices.SayHelloBidirectionalStreaming:input_type -> HelloRequest
	1, // 4: GreetServices.SayHello:output_type -> HelloResponse
	1, // 5: GreetServices.SayHelloServerStreaming:output_type -> HelloResponse
	4, // 6: GreetServices.SayHelloClientStreaming:output_type -> MessagesList
	1, // 7: GreetServices.SayHelloBidirectionalStreaming:output_type -> HelloResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greet_proto_init() }
func file_proto_greet_proto_init() {
	if File_proto_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greet_proto_rawDesc), len(file_proto_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greet_proto_goTypes,
		DependencyIndexes: file_proto_greet_proto_depIdxs,
		MessageInfos:      file_proto_greet_proto_msgTypes,
	}.Build()
	File_proto_greet_proto = out.File
	file_proto_greet_proto_goTypes = nil
	file_proto_greet_proto_depIdxs = nil
}
